# last-translation-benchmark configuration file

OPENAI_API_KEY = ""
DEEPL_API_KEY = ""
LIBRE_API_KEY = ""
LIBRE_URL = ""
OPENROUTER_API_KEY = ""

CONTRIBUTOR_QUOTA_DEFAULT = 10
DB_PATH = "data/db.sqlite"
